name: CI

on:
  # Trigger CI on push to production or master
  push:
    branches: ["production", "master"]
  pull_request:
    branches: ["master"]

  # Trigger CI after the release workflow completes
  workflow_run:
    workflows: ["Automated Release and Notification"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
