name: Automated Release and Notification

on:
  push:
    branches:
      - production
jobs:
  release:
    name: Automated Release
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged == true
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git
        run: |
          git config --global user.name "Mani sankar"
          git config --global user.email "manisnakr4893@gmail.com"

      - name: Run Release Script
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          REPO_OWNER: "manisankar-divi" # Replace with your GitHub username q
          REPO_NAME: "k8s-repo" # Replace with your repository name
        run: |
          bash ./release.sh
