name: Release Notification

on:
  release:
    types: [published]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Process the release body to add newlines and format headers
      - name: Process release body
        id: process-body
        run: |
          # Extract and process the release body to replace markdown headers with newlines and add proper formatting
          PROCESSED_BODY=$(echo "${{ github.event.release.body }}" | sed -E 's/### (.*)/\n*\\1*:/g; s/## (.*)/\n*\\1*:/g; s/^-\s*/- /g')

          # Output the processed body to GITHUB_ENV for use in subsequent steps
          echo "processed_body=$PROCESSED_BODY" >> $GITHUB_ENV

      # Step 2: Send a Slack notification with the release details
      - name: Send Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "A new release is published: ${{ github.event.release.tag_name }}"
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ github.event.release.tag_name }} is published!"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Author:*\n${{ github.event.release.author.login }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Published At:*\n${{ github.event.release.published_at }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Release Notes:*\n${{ env.processed_body }}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Release",
                      "emoji": true
                    },
                    "url": "${{ github.event.release.html_url }}"
                  }
                ]
              }
            ]
